### ISSUE TITLE
Zelfevaluatie Valide Code en Correcte Aria

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#913]
Ik wil de derde zelfevaluatie van de toolkit opstarten met als thema "valide code en correcte aria". Dit betekent dat ik alle componenten ga valideren en handmatig doorlees met bijzondere aandacht voor aria, als ik codefouten of verkeerd aria gebruik constateer maak ik issues aan en ik houd aantekening in mijn spreadsheet. Er komt natuurlijk ook weer een zelfevaluatie rapportje uit. Vragen:  
* Valideren jullie de code zelf al systematisch en zo ja hoe?
* Ik wil de code valideren met de w3c content markup validation service door voor ieder component de voorbeeldcode in een kale html5 pagina te plakken die ik op mijn server zet en valideer. Dan staat het resultaat los van dso-toolkit.nl. Ik kan de code handmatig copy-pasten of is er een makkelijke manier om de voorbeeldcode in 1 bestandje per component uit te checken? Dat zou me veel tijd schelen, dan kan ik het grotendeels automatiseren en met een nieuwe versie makkelijker herhalen 
* De css kan ook gevalideerd worden. Welke css bestanden moet ik valideren?

Deze week ga ik hier nog niet aan toe komen, zullen we dit donderdag bespreken zodat we samen een plan kunnen maken?

**Comment by bramhoosemans** [comment]
Wens is om een geautomatiseerd validatie proces te integreren in de DSO Toolkit en losse teams. Tim pakt dit op begin 2021. Wordt vervolgd.

**Comment by timveld** [comment]
Ik vertrouwde de uitspraak "je hoeft je geen zorgen te maken over valide CSS want dat hebben we goed geregeld" niet helemaal. Waarschijnlijk terecht: de eerste de beste pagina bevat volgens de w3c validation service het deprecated element "max-device-width", zie https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.dso-toolkit.nl%2F15.0.1%2Fstyles%2Fdso.css Is deze validator niet goed / te streng of...?

**Comment by tfrijsewijk** [comment]
Hi Tim,

Zoals eerder aangegeven lijkt het mij niet de bedoeling dat jij je bezig houdt met het valideren van de CSS. Dit is een build artifact en de deprecated feature name "max-device-width" is niet het enige probleem wat de w3 validator meldt.

En dit is by design: De styling van de toolkit wordt in SCSS geschreven en gecompileerd naar CSS en door PostCSS nabewerkt. Hiermee leveren we CSS die nieuwe EN oude browsers bedient. Het nastreven van een perfect CSS Level 3 implementatie was tot voor kort zelfs een nobel streven - en niet meer dan dat. 

Een van de aspecten van een CSS implementatie is hoe om te gaan met onbekende of ongeldige styling. Uitgangspositie is dat de betreffende styling wordt genegeerd. En daar is het hele systeem dan ook op gebasseerd: Ja, `max-device-width` is deprecated en moeten we eruit halen, maar iets verderop staat dezelfde media query maar dan met `max-width` waardoor er over een breder scale aan user agents alsnog de gewenste media query actief is.

Onze broncode valideren wij met een linter (Stylelint). De code van Bootstrap is hier bewust buiten gehouden. Bij de verhuizing van de styling naar `@dso-toolkit/styling` fuseren we de DSO styling en de Bootstrap styling waarmee we de Bootstrap broncode ook gaan linten en vanzelfspreken conform de linter zullen inchecken.

Ik denk niet dat wij ooit CSS gaan valideren, aangezien ik je eerder kan garanderen dat er géén compatible CSS3 wordt gegenereerd dan wel. En dat maakt niet uit. Overigens zal het natuurlijk steeds meer richting CSS3 gaan, helemaal nu we geen IE11 (en IE Legacy) meer hoeven te ondersteunen en de styling van Bootstrap gaan.

Ik heb een paar andere sites door de door jouw aangedragen validator gehaald.. En de enige site die valideerde was de w3 site zelf. Gov.uk design system, mijn top 10 sites, de top 5 "best accessible sites 2020" valideren allemaal niet.

Volgens mij is ons doel niet om geldige CSS3 op te leveren, maar een toegankelijke site. Dat het dan geen geldige CSS3 is hoeft geen probleem te zijn. En het is zeker niet een probleem wat je alleen met een CSS3 validator gaat vinden maar op z'n minst met de geldende markup als context.

Ik hoop dat ik met bovenstaande uiteenzetting het valideren van de CSS kan laten rusten en dat ik je vertrouwen weer heb teruggewonnen :)

**Comment by timveld** [comment]
Bedankt voor de uitleg. Valide CSS is geen eis vanuit WCAG, dus we kunnen in ieder geval bepaalde afwijkingen zoals deprecated properties negeren. 

Als ik het goed begrijp garandeert het buildproces wel correcte syntax. 
We moeten streven naar CSS3 maar hoeven daar inderdaat niet direct volledig aan te voldoen. 
Wel roept je verhaal bij mij de vraag op of we N.A.V. het stoppen met internet explorer een schoonmaakactie moeten houden zodat zo veel mogelijk onnodige CSS verdwijnt. In principe wordt deprecated troep genegeerd, maar het is wel altijd een extra complicatie. Al is het maar voor de implementator die de oorzaak van een bug probeert te vinden en de extra regel moet lezen. User agents die we willen ondersteunen profiteren volgens mij in geen geval van deprecated properties. Dus "opgeruimd staat netjes" lijkt me een belangrijk uitgangspunt, alle troep die je laat liggen geeft struikelgevaar en vertroebelt mogelijk het oplossen van problemen.

**Comment by timveld** [comment]
En ik heb voor een paar componenten de voorbeeldcode gevalideerd, bij treeview heb ik de eerste afwijking gevonden. De meeste voorbeeldcode geeft foutmeldingen op de gebruikte id's (ontbrekend, dubbel, met spatie en dergelijke). als we automatisch willen valideren dan moeten we de voorbeelden op dit punt aanpassen maar handmatig kan ik deze fouten wel negeren. Hetzelfde geldt voor bijvoorbeeld de main tag in de wizard stap 1 die conflicteert met een bestaande main tag in de testpagina waarin ik het plak. Ik ben toch geneigd de 50 stukjes voorbeeldcode handmatig door te lopen, dat is een klusje (maar als ik de voorbeeldjes in losse bestandjes kan krijgen valt het heel erg mee) en dan kan ik gelijk kritisch de aria meenemen. Misschien moeten we de toolkit niet automatisch willen valideren (want dan moet je echt zorgen dat de voorbeelden helemaal kloppen) maar alleen de resulterende applicaties valideren en handmatig zorgen dat er bij de bron geen fouten zitten.

**Comment by timveld** [comment]
Als donderdag besproken gaan we hier mee verder als er een plan is voor de grotendeels automatische test. Dit neem ik ook mee in het project automatisch testen waar we in januari mee starten.

**Comment by MichielDHVD** [comment]
@timveld Ik ga dit issue sluiten aangezien je het hebt afgerond. Dit staat intern op confluence en jira juist gedocumenteerd. 

Dit issue zal niet leiden tot een github release issue dus daarom sluit ik het en mag het als afgerond beschouwd worden.
